### ISSUE TITLE
Commands doesnt execute without restart

### ISSUE THREAD

**Issue by SirSuso** [BuycraftPlugin/BuycraftX#10]
Hello as the title says, I have to restart between every donations to make them receive the package they bought. I am running an bungee network with ip_forward to true in bungee config and bungeecord to true in spigot. Also latest spigot and latest buycraft x.

**Comment by minecrafter** [comment]
Did you get any exceptions from BuycraftX? I verified multiple times that multiple purchases do work with BuycraftX, so this is probably an issue in your setup.

**Comment by SirSuso** [comment]
It has always worked before, so what you mean by my setup and exceptions?

**Comment by minecrafter** [comment]
Without further details, I can not possibly fix the issue.

**Comment by SirSuso** [comment]
what details you want me to send you?

**Comment by minecrafter** [comment]
I need to know any exceptions or errors BuycraftX has sent in your logs. Do not restart the server.

Also note that BuycraftX requests commands every 90 seconds. Please wait at least 90 seconds for purchases to apply.

**Comment by SirSuso** [comment]
Have been waiting few hours for purchases to apply. + Its not giving any errors in console.

**Comment by minecrafter** [comment]
Are you using Beta 2?

**Comment by SirSuso** [comment]
I havent tested it with the beta 2 yet. Just installed it so hopefully it works. And btw can I ask how to turn on the offline option in the buycraft panel? Cant see it anymore. Since I want commands to execute even if the player is not on the server.

**Comment by SirSuso** [comment]
Btw the commands did not execute now, got a new donation we have been waiting 10 minutes, but nothing happens again. (Latest spigot and latest buycraft x 2)

**Comment by minecrafter** [comment]
What happens when you force a check? (`/buycraft forcecheck`)

**Comment by boblemon1337** [comment]
**edit** I'm still doing testing, I have similar issues to the OP but a '/plugman reload' of the BuycraftX plugin followed by '/buycraft forcecheck' currently is fixing the issue.

**Comment by minecrafter** [comment]
@mcarey10 What happens when you force a check while commands do not execute? (`/buycraft forcecheck`)

**Comment by SirSuso** [comment]
For me it just says forcechecking then nothing happened

**Comment by SirSuso** [comment]
or it doesnt say force checking, but gives you the message when you do /buycraft forcecheck, then nothing happens

**Comment by minecrafter** [comment]
Does it say "We're currently checking for new purchases. Sit tight!" or "Successfully queued player check."?

**Comment by SirSuso** [comment]
the first one.

**Comment by boblemon1337** [comment]
After restarting the server, forcecheck will say the second one in green, which for me correlated with the forcecheck successfully running the commands after the payment. When the plugin was bugged, it would say the first one, and the commands wouldn't run; in the buycraft web panel they would still say 'due' as well.

**Comment by minecrafter** [comment]
Please try [this build](https://minecraft.minimum.io/downloads/buycraftx-fix-10.jar).

**Comment by boblemon1337** [comment]
So far so good, I'll keep you posted.

**Comment by SirSuso** [comment]
@mcarey10 tell me if worked! :)

**Comment by LeeMcNeil** [comment]
@mcarey10 @SirSuso Is this issue resolved for you guys? Please let us know so we can resolve this issue if so - thank you.

**Comment by SirSuso** [comment]
Yes its resolved! :) Thanks for the help.

Date: Wed, 17 Feb 2016 06:04:51 -0800

**Comment by LeeMcNeil** [comment]
@SirSuso Thanks for the update - have a good day.

**Comment by sebastianbinder** [comment]
Is there an updated Build for the BungeeCord plugin as well? I'm experiencing the same issues there...

**Comment by minecrafter** [comment]
@sebastianbinder The BungeeCord build is also affected, that's correct. There's no compiled build for that but the latest version on Git does work.

**Comment by sebastianbinder** [comment]
@minecrafter okay. thank you! just built the version on git. let's see if it works :)
