### ISSUE TITLE
BuycraftX/Tebex doesnt auto check for payments

### ISSUE THREAD

**Issue by ghost** [BuycraftPlugin/BuycraftX#129]
As the title says when I do a manual payment on Tebex, it goes thru but until I do /buycraft forcecheck, nothing happens ingame!
Please help!

**Comment by Torbikini** [comment]
Have you tried enabling push commands? If you don't enable that setting payments will not be instant.

**Comment by liam-wiltshire** [comment]
Please contact our support channels for help with this. Issues are for specific code bugs only
