### ISSUE TITLE
Incorrect Items shown in /buy

### ISSUE THREAD

**Issue by andrewkm** [BuycraftPlugin/BuycraftX#138]
This is not fixed: https://github.com/BuycraftPlugin/BuycraftX/issues/134

**Comment by liam-wiltshire** [comment]
As you know we did previously try to fix this,, however if that hasn't resolved it, then unfortunately we will not be able to fix this - it is quite a corner case, running different versions above and below the 1.12/1.13 divide, so there isn't really a viable solution that we can recommend unfortunately.
