### ISSUE TITLE
Sugesstion suggestion for subcommands.

### ISSUE THREAD

**Issue by SrBedrock** [BuycraftPlugin/BuycraftX#144]
Add suggestion for subcommands.

After typing the command `/tebex` and space, the plugin will suggest all available subcommands.

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to provide this suggestion, I'm sorry it's been slow to reply to your idea — we're working on it!

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and I will happily note this idea down for the recode.

Thanks for providing a cool suggestion :)
