### ISSUE TITLE
Error with BuycraftListener.onPlayerJoin

### ISSUE THREAD

**Issue by SrBedrock** [BuycraftPlugin/BuycraftX#146]
https://hasteb.in/vuwijabu.shell

**Comment by andrewkm** [comment]
Downgrade from 12.0.5 to 12.0.4
12.0.5 lags server (on player joins) and crashes server on **heavy** joins/player server->server transfers.
12.0.4: https://ci.ecocitycraft.com/job/BuycraftX/62/ (Unofficial build server hosted by myself).
