### ISSUE TITLE
Fabric

### ISSUE THREAD

**Issue by Ueaj-Kerman** [BuycraftPlugin/BuycraftX#156]
Are you interested in a fabric port of Buycraft? (Assuming I PR one)

**Comment by SkyNetCloud** [comment]
I was really hoping for there to be verison of this for fabric but I get I was wrong

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to submit your feedback, a Fabric port is under way but isn't yet production ready.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and so maybe it is worth holding back your port until we have completed that.

Thank you for your offer!
