### ISSUE TITLE
Issue from support

### ISSUE THREAD

**Issue by hfmachin** [BuycraftPlugin/BuycraftX#16]
'' WARN Exception in thread "Craft Scheduler Thread - 2" 
27.02 06:22:19 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin BuycraftX v0.1.1-SNAPSHOT generated an exception while executing task 219 ''

Let me know if you need more info.

**Comment by minecrafter** [comment]
Not enough information to see if there is an actual issue.

Getting the full stack trace would be nice.

**Comment by hfmachin** [comment]
27.02 15:31:02 [Server] WARN Exception in thread "Craft Scheduler Thread - 13" 
27.02 15:31:02 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin BuycraftX v0.1.1-SNAPSHOT generated an exception while executing task 130 
27.02 15:31:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56) 
27.02 15:31:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
27.02 15:31:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
27.02 15:31:02 [Server] INFO at java.lang.Thread.run(Thread.java:745) 
27.02 15:31:02 [Server] INFO Caused by: java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder 
27.02 15:31:02 [Server] INFO at net.buycraft.plugin.client.ProductionApiClient.<init>(ProductionApiClient.java:19) 
27.02 15:31:02 [Server] INFO at net.buycraft.plugin.bukkit.command.SecretSubcommand$1.run(SecretSubcommand.java:35) 
27.02 15:31:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) 
27.02 15:31:02 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 
27.02 15:31:02 [Server] INFO ... 3 more 
27.02 15:31:02 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder 
27.02 15:31:02 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:372) 
27.02 15:31:02 [Server] INFO at java.net.URLClassLoader$1.run(URLClassLoader.java:361) 
27.02 15:31:02 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) 
27.02 15:31:02 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:360) 
27.02 15:31:02 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) 
27.02 15:31:02 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) 
27.02 15:31:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
27.02 15:31:02 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
27.02 15:31:02 [Server] INFO ... 7 more

This is what the same guy sent in another email.. though I'll try and get the full stack trace for the other.

**Comment by minecrafter** [comment]
User is using very old 1.8 build. They should update.
