### ISSUE TITLE
RecentPayment get package (name)

### ISSUE THREAD

**Issue by RobiRami** [BuycraftPlugin/BuycraftX#17]
Hi,

There doesn't seem to be a way to get a package id or package name from a RecentPayment object.
Am I missing something ?

Thanks

**Comment by minecrafter** [comment]
It's not included in the API response. I've gotten some private requests for adding packages purchased however, we'll see about that.

**Comment by minecrafter** [comment]
Closing as this is not a BuycraftX issue
