### ISSUE TITLE
Is this plugin ever updated?

### ISSUE THREAD

**Issue by ghost** [BuycraftPlugin/BuycraftX#173]

**Comment by LeeMcNeil** [comment]
If you have a specific issue or bug please reach out to customer support - our plug-in is maintained and is stable 😊

**Comment by ghost** [comment]
can you give me a link to where the plugin is maintained? the plugin hasn't been updated on spigotmc or devbukkit.

**Comment by LeeMcNeil** [comment]
You can download it from the plugins section under Integrations within the Tebex control panel - https://server.tebex.io
