### ISSUE TITLE
Coupon Creation Error

### ISSUE THREAD

**Issue by zPqguro03** [BuycraftPlugin/BuycraftX#195]
`[BuycraftX] Plugin BuycraftX v12.0.8 generated an exception while executing task 94930
java.lang.reflect.UndeclaredThrowableException: null
	at jdk.proxy13.$Proxy86.createCoupon(Unknown Source) ~[BuycraftX.jar:?]
	at net.buycraft.plugin.bukkit.command.CouponSubcommand.lambda$createCoupon$0(CouponSubcommand.java:55) ~[BuycraftX.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles$Lookup.<init>(java.lang.Class,int)
	at java.lang.Class.getConstructor0(Class.java:3585) ~[?:?]
	at java.lang.Class.getDeclaredConstructor(Class.java:2754) ~[?:?]
	at net.buycraft.plugin.internal.retrofit2.Platform$Java8.invokeDefaultMethod(Platform.java:102) ~[BuycraftX.jar:?]
	at net.buycraft.plugin.internal.retrofit2.Retrofit$1.invoke(Retrofit.java:145) ~[BuycraftX.jar:?]
	... 8 `more``

**Comment by Disorbs** [comment]
bumping this as im now facing this issue as well please fix this someone said it has to do with java 17?

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

If your issue still exists, please reply here and I'll look into getting them fixed.

Apologies for the issues you have faced!

**Comment by skycar** [comment]
Hello, any updated ETA for this update? 

I'm facing this exact issue on Java 17 and no console commands are working either as well as the API (intended for a custom plugin that creates coupons/gift cards automatically for players).

**Comment by entity** [comment]
> Hello, any updated ETA for this update?
> 
> I'm facing this exact issue on Java 17 and no console commands are working either as well as the API (intended for a custom plugin that creates coupons/gift cards automatically for players).

Hey Skycar! Apologies that you’re facing this same issue, as mentioned above we are in the planning stages with a new plugin.

Please use the dashboard for that functionality for now, and I’ll give you an update once we have our new plugin.

**Comment by skycar** [comment]
Hi, thanks for the quick response. Is there an approximate timeline in terms of when you expect said new plugin to be completed?

**Comment by skycar** [comment]
As we are approaching the midpoint of Q2.

**Comment by entity** [comment]
> Hi, thanks for the quick response. Is there an approximate timeline in terms of when you expect said new plugin to be completed?

I completely understand, we hope to get a beta out in this quarter :)

**Comment by skycar** [comment]
Ok great. Will this jar be posted on the Tebex website, Spigot or both?

**Comment by entity** [comment]
> Ok great. Will this jar be posted on the Tebex website, Spigot or both?

Once it’s out officially, we will aim to have it posted everywhere. Stay tuned! :)

**Comment by skycar** [comment]
How do I get access to the beta? And how long will the beta period last/how much longer until the plugin’s released officially?

**Comment by Disorbs** [comment]
> How do I get access to the beta? And how long will the beta period last/how much longer until the plugin’s released officially?

that guy is a troll btw lol who knows if its being worked on by the actual devs

**Comment by skycar** [comment]
Rip lmao. & I hope it is

**Comment by entity** [comment]
> > How do I get access to the beta? And how long will the beta period last/how much longer until the plugin’s released officially?
> 
> that guy is a troll btw lol who knows if its being worked on by the actual devs

I’m not a troll, I work at Tebex :)

Long time no speak Disorbs too haha, I joined in October after the acquisition of Analyse.

**Comment by entity** [comment]
Hi again,

I'm just following up to let you know that we have now added this bug to our internal tracking system.

Our team is currently working on a number of important projects, including a recode of the Buycraft plugin this quarter. We will keep your bug in mind as we work on this update and will note it in our development roadmap.

Since we have now noted your bug in our internal tracking system, we will be closing this GitHub ticket. However, if you have any further suggestions or feedback, please don't hesitate to open a new ticket and we'll be happy to take a look.

Thanks again for reporting this bug and for your continued support of Tebex.

Best regards,
The Integrations Team.
