### ISSUE TITLE
Sign message spam

### ISSUE THREAD

**Issue by SirSuso** [BuycraftPlugin/BuycraftX#2]
Its spamming "unable to locate sign at (and then some cords)" randomly in chat. And when players is breaking blocks it spamming this: You don't have permission to break this sign.

**Comment by LeeMcNeil** [comment]
Hey @SirSuso, could you please provide some details about your setup? Such as Spigot version etc. Our developer @minecrafter will get onto this as soon as he can. Thanks

**Comment by SirSuso** [comment]
VERSION:
12.02 06:40:54 [Server] INFO You are 6 version(s) behind
12.02 06:40:54 [Server] INFO Checking version, please wait...
12.02 06:40:54 [Server] INFO This server is running CraftBukkit version git-Spigot-db6de12-07c3001 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by minecrafter** [comment]
"unable to locate sign at (and then some cords)" is a message from Minecraft.

The last issue is actually a plugin issue. It's fixed now.

**Comment by SirSuso** [comment]
Stupid question: Where do I found the new updated version?

**Comment by minecrafter** [comment]
You'll have to compile it from the repository or wait for us to release a new beta build.

**Comment by SirSuso** [comment]
Will it be long until you release the new beta?
