### ISSUE TITLE
[BuycraftX] Could not fetch due players queue

### ISSUE THREAD

**Issue by sovtec** [BuycraftPlugin/BuycraftX#205]
https://pastebin.com/xcrqrv8g

Server version *Paper version git-Paper-102 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 13c9d3c)*

plugin version *BuycraftX version 12.0.8*

**Comment by vaniron** [comment]
Also happening on 1.16.5 server: https://pastebin.com/raw/LAD8bvZQ

**Comment by hedrizzle** [comment]
And on 1.20.2 / Paper-Purpur: https://pastebin.com/a4TykRS5

**Comment by hedrizzle** [comment]
can i ask on which OS you are? i bet on Windows Server, right? @aglarcz @sovtec

I think i just found **the solution**:
i have excluded my entire minecraft server folder from windows defender and now it seems to work!

**Comment by sovtec** [comment]
> can i ask on which OS you are? i bet on Windows Server, right? @aglarcz @sovtec
> 
> 
> 
> I think i just found **the solution**:
> 
> i have excluded my entire minecraft server folder from windows defender and now it seems to work!

Linux, still having issues by the way, kinda annyoing getting a buycraft warning every hour

**Comment by hedrizzle** [comment]
and some anti-virus package installed on the linux distribution?

**Comment by vaniron** [comment]
I am on Ubuntu without any antivirus.

**Comment by hedrizzle** [comment]
nvm, the error is back.

**Comment by AceSardonyx** [comment]
This is an ancient issue. They are refusing to fix it or they have already fixed it in the new rewrite of the plugin that we do not know when is coming out. 
Bump to at least fix the verbose option with this.
I recommend getting console spam fix plugin.

**Comment by NixsSa2d** [comment]
They didn't say any solution

**Comment by AceSardonyx** [comment]
> They didn't say any solution

Yeah, the solution is that we have to wait for BuyCraft v2 to come out 😂 
But I feel as if it would be realllllyyyy easy to release a hotfix that *fixes* the verbose issue so it would make waiting for v2 more bearable.

**Comment by sovtec** [comment]
> This is an ancient issue. They are refusing to fix it or they have already fixed it in the new rewrite of the plugin that we do not know when is coming out. 
> 
> Bump to at least fix the verbose option with this.
> 
> I recommend getting console spam fix plugin.

ConsoleSpamFix helps a lot actually but it's kinda (really) annoying having this issue occur every 10 min

**Comment by sovtec** [comment]
> > They didn't say any solution
> 
> 
> 
> Yeah, the solution is that we have to wait for BuyCraft v2 to come out 😂 
> 
> But I feel as if it would be realllllyyyy easy to release a hotfix that *fixes* the verbose issue so it would make waiting for v2 more bearable.

I have actually emailed them a few times but the only thing they say is _Thank you for your feedback. We will pass this on to our developers as they are already working on improving this functionality._

This was in Juli 2022.. that's 16 months since

They have also said _"Thanks for getting in touch about the console errors you're receiving. Please can you confirm roughly how often you receive these error messages?
If they're just occasional errors then it's likely to be a transient network issue when the plugin tries to call our API. We are working to improve the API's performance which should mean that these errors become less frequent."_

**Comment by ImSnipper** [comment]
Any update on this?????????????

**Comment by sovtec** [comment]
> Any update on this?????????????

Not yet, email them and ask about progress I guess

**Comment by WildBamaBoy** [comment]
Hey there, we've identified this as a problem with our API infrastructure and have made the needed fixes. This should no longer be a recurring problem.
