### ISSUE TITLE
BuycraftX disabling on startup. Paper 1.20.1 Build 156

### ISSUE THREAD

**Issue by Goldenphelix** [BuycraftPlugin/BuycraftX#206]
Hello I've just recently updated to 
Paper 1.20.1 build 156
Using BuycraftX v12.0.8
And buycraft is disabling itself on startup?
I've tried removing the buycraft plugin folder and do a fresh install and but it still shows the error below.
I've had to disable my tebex store until this is fixed, any help would be appreciated..

`22.08 20:51:46 [Server] ERROR Error occurred while enabling BuycraftX v12.0.8 (Is it up to date?)
22.08 20:51:46 [Server] INFO java.lang.RuntimeException: Unable to inject channel futures.
22.08 20:51:46 [Server] INFO at net.buycraft.plugin.bukkit.httplistener.NettyInjector.inject(NettyInjector.java:156) ~[BuycraftX.jar:?]
22.08 20:51:46 [Server] INFO at net.buycraft.plugin.bukkit.BuycraftPluginBase.onEnable(BuycraftPluginBase.java:140) ~[BuycraftX.jar:?]
22.08 20:51:46 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
22.08 20:51:46 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
22.08 20:51:46 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
22.08 20:51:46 [Server] INFO Caused by: java.lang.NoSuchMethodException: net.minecraft.server.MinecraftServer.getServerConnection()
22.08 20:51:46 [Server] INFO at java.lang.Class.getDeclaredMethod(Class.java:2675) ~[?:?]
22.08 20:51:46 [Server] INFO at net.buycraft.plugin.bukkit.httplistener.NettyInjector.inject(NettyInjector.java:64) ~[BuycraftX.jar:?]
22.08 20:51:46 [Server] INFO ... 13 more
22.08 20:51:46 [Server] INFO [BuycraftX] Disabling BuycraftX v12.0.8
22.08 20:51:46 [Server] ERROR Error occurred (in the plugin loader) while disabling BuycraftX v12.0.8 (Is it up to date?)
22.08 20:51:46 [Server] INFO java.lang.NullPointerException: Cannot invoke "net.buycraft.plugin.shared.config.signs.storage.RecentPurchaseSignStorage.save(java.nio.file.Path)" because "this.recentPurchaseSignStorage" is null
22.08 20:51:46 [Server] INFO at net.buycraft.plugin.bukkit.BuycraftPluginBase.onDisable(BuycraftPluginBase.java:276) ~[BuycraftX.jar:?]
22.08 20:51:46 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
22.08 20:51:46 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
22.08 20:51:46 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
22.08 20:51:46 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-156]
22.08 20:51:46 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Goldenphelix** [comment]
Okay, setting `push-commands=false` in the BuycraftX config.properties fixes this error from showing up?

**Comment by WildBamaBoy** [comment]
For Paper 1.20 and above please prefer the new plugin located at: https://github.com/tebexio/Tebex-Minecraft
