### ISSUE TITLE
Creating buysigns

### ISSUE THREAD

**Issue by AshourAziz** [BuycraftPlugin/BuycraftX#21]
#15 I don't get how you can DEFINE The location for buysigns, previously (as mentioned in #15) it was /buysigns I don't understanding the explanation provided in #15

**Comment by minecrafter** [comment]
Are you talking about placing the signs down, or showing how recent the purchase was?

**Comment by AshourAziz** [comment]
Looking to place  signs and show for example the recent 10 donations to the server.
Previously I believe we placed down the signs and then performed /buysigns start and /buysigns end at the starting/ending sign.

**Comment by minecrafter** [comment]
With BuycraftX, you're still placing down 10 signs, but you'll have to use some sign text:

```
[buycraft_rp]
<position>
```

`<position>` would be in order from 1 to 10.

It'll be more clear once we have a video made for this.

**Comment by AshourAziz** [comment]
I understand now thanks for the clarification.
