### ISSUE TITLE
huge lag spikes looping over player list

### ISSUE THREAD

**Issue by tonyjamesstark** [BuycraftPlugin/BuycraftX#210]
There seems to be some correlation on our server between buycraft player list checks and large lag spikes. The console issues the messages:
```
[BuycraftX] Fetching all due players...
[BuycraftX] Fetched due players (15 found).
```
and at other times
```
[BuycraftX] Sending 1 analytic events
```
during these times. 

please advise! is there a way to maybe make these checks asynchronous or distribute the load?

Thanks,
A concerned server admin

**Comment by tonyjamesstark** [comment]
looks like it is already async, but a new object is instantiated every time the check runs, not sure if this could be related:
https://github.com/tebexio/BuycraftX/blob/ec99b1ef7b412f1add2dc81ab273ca6619759bf9/bukkit-shared/src/main/java/net/buycraft/plugin/bukkit/BuycraftPluginBase.java#L148

the messages above are within these classes: 
https://github.com/tebexio/BuycraftX/blob/ec99b1ef7b412f1add2dc81ab273ca6619759bf9/common/src/main/java/net/buycraft/plugin/execution/DuePlayerFetcher.java
https://github.com/tebexio/BuycraftX/blob/ec99b1ef7b412f1add2dc81ab273ca6619759bf9/common/src/main/java/net/buycraft/plugin/execution/ServerEventSenderTask.java

**Comment by WildBamaBoy** [comment]
Hi there, BuycraftX is no longer supported as of January 2, 2024. Here's the repository for our new Minecraft plugin: https://github.com/tebexio/Tebex-Minecraft

The new plugin can automatically migrate from your BuycraftX config once installed. If there are any lag issues with the new plugin please submit an issue in the other repository.
