### ISSUE TITLE
Rank-up issues in only a certain world.

### ISSUE THREAD

**Issue by ericbarbwire** [BuycraftPlugin/BuycraftX#22]
Hello, I run a Spigot server running version: Spigot-b1c1b55-7d73fbb
I am currently using the latest Buycraft plugin found on the blog.
Basically when any users purchases the "Bronze" rank, they are upgraded in all worlds except from the Games world.
http://hastebin.com/girozejisi.vbs and http://hastebin.com/yokanicaho.vbs
I have since removed the initial command that ranks up the user, however this issue still persists.
It keeps trying to rank up the user, even when there is no issue at all.
Any sort of help would be really appreciated.
Also, when this happens my TPS absolutely tanks and spams console.

**Comment by minecrafter** [comment]
This isn't a BuycraftX issue, and GroupManager is deprecated. Try switching to another permission plugin.

**Comment by minecrafter** [comment]
For reference: if a command fails, BuycraftX will attempt to rerun it. You may want to remove the due command from the panel.

**Comment by ericbarbwire** [comment]
The due command is removed, but it still tries to rerun it over and over again.

**Comment by minecrafter** [comment]
Try restarting the server.

**Comment by ericbarbwire** [comment]
This is an ongoing issue, I removed the due command a few days ago, everytime I restart the server the issue still persists as soon as that user joins the game.

**Comment by minecrafter** [comment]
I will add in a mitigation so that failed commands do not get repeatedly executed.

**Comment by ericbarbwire** [comment]
Thank you very much! You have saved my server tons of lag!

**Comment by ericbarbwire** [comment]
Hey, this issue still persists while using Buycraft 10.0
Here's an example: http://hastebin.com/ibasiqidos.vbs
 http://hastebin.com/awihaxopav.vbs
It keeps repeating "04.04 22:41:39 [Server] ERROR [BuycraftX] Could not dispatch command 'manuaddp ArrowheadDip donor' for player 'ArrowheadDip'. This is typically a plugin error, not an issue with BuycraftX." causing my server to lag greatly. But it doesn't show any issues for ranking up users. Just the perms. I'd really appreciate a fix.

**Comment by minecrafter** [comment]
This would be a GroupManager issue. BuycraftX does not have any control over how GroupManager operates.

**Comment by ericbarbwire** [comment]
The issue is that after the command fails to run, it still keeps trying to execute causing the server to lag greatly.
The issue keeps happening whenever that user is online.

**Comment by minecrafter** [comment]
You can delete the command from your web panel.

**Comment by ericbarbwire** [comment]
Even after removal the issue continues to happen.
Maybe this was not fully implemented yet? "I will add in a mitigation so that failed commands do not get repeatedly executed."

**Comment by minecrafter** [comment]
This was already implemented. I am not sure why the command is still trying to execute though. Try restarting.
