### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by clienthax** [BuycraftPlugin/BuycraftX#24]
new SerializedBlockLocation(((World)location.getExtent()).getName(), location.getBlockX(), location.getBlockY(), location.getBlockZ());

Worlds can share the same name, use the unique id of the world instead.

**Comment by minecrafter** [comment]
Beta 3 has already been released with the code. I will change it, but we'll have to remind people to redo recent purchase signs if they're using Sponge. We're not expecting a significant number of people using Sponge at this time, however,
