### ISSUE TITLE
GUI item ID

### ISSUE THREAD

**Issue by Johandrex** [BuycraftPlugin/BuycraftX#25]
The "GUI item ID" that is set in a category on Buycraft doesn't display using "/buy" in game.

**Comment by minecrafter** [comment]
This is on purpose:
- Item IDs are meaningless with standalone execution and the BungeeCord plugin.
- Item IDs are deprecated by Mojang.
- You can't use item IDs with Sponge.

**Comment by FarisR99** [comment]
Why not remove it from the BuyCraft website store then?

**Comment by Gaurav99** [comment]
I'm not sure I fully understand your response, are you saying that the /buy GUI will no longer be customizable/supported?

**Comment by LeeMcNeil** [comment]
With the new control panel being released soon the gui item ID will not be
configurable. I'll have a chat with tux to see if there is anything we can
do to implement a similar feature in the future.

On Saturday, 16 April 2016, Gaurav99 <notifications@github.com> wrote:

> I'm not sure I fully understand your response, are you saying that the
> /buy GUI will no longer be customizable/supported?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BuycraftPlugin/BuycraftX/issues/25#issuecomment-210831515>
>


-- 
Regards

Lee McNeil
Founder

Mobile: +44 (0) 7729303988
Email: lee@tebex.co.uk
Skype: lee.j.mcneil

Tebex Limited Registered in England & Wales No. 08129184.
