### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by AshourAziz** [BuycraftPlugin/BuycraftX#27]
Having issues that buycraftX does not get new transactions after several hours of the server being up. ./buycraft forcecheck doesn't solve it either. I'm in contact with support & was told to "update to release 3" I have done so and the issues still are going on -- I emailed back with a new /buycraft report

That being said, on the blogpost: https://blog.buycraft.net/introducing-the-public-beta-of-the-new-bukkit-plugin/

beta-3 is what I'm using -- I cannot tell how old this and up to what commits are in that build is there a 100% up to date compiled version I can test that hopefully will resolve my issues?

**Comment by minecrafter** [comment]
Beta 3 is based on 0145174.

I think I've resolved the main underlying issue in this case now (see the commit I pushed).

While we do have auto-compiled builds, they're internal. You can however compile from this repository.

**Comment by AshourAziz** [comment]
~14 hours of uptime and it's still processing purchases fine. So it seems like it has resolved it for now.
