### ISSUE TITLE
Suggestion - Buycraft signs

### ISSUE THREAD

**Issue by Johandrex** [BuycraftPlugin/BuycraftX#28]
I'd like to add signs in game that shows the current price on a package and sends you the purchase link if you press the sign. This would be very useful for my and other servers as we're often having sales & discounts.

https://gyazo.com/f7bf390793dbc102d9f859a8777352d3

https://gyazo.com/eb011a95c503ea2e0f5ed1f71e9bc616

**Comment by minecrafter** [comment]
This is already implemented. Just create a sign with " [buycraft_buy]" 
as the first line and it'll let you select a package to put on the sign.

**Comment by Johandrex** [comment]
Ah awesome, would be nice if we could change the layout on the sign though.
