### ISSUE TITLE
BungeeCord 0.1.3 {uuid} placeholder not working

### ISSUE THREAD

**Issue by johnfriedrich** [BuycraftPlugin/BuycraftX#30]
Hi,
we are running 0.1.3 on our BungeeCord.
online-mode: true

We wanna use this bungeeplugin to set BungeePerms groups.

This is our buycraft command:
bp user {uuid} group set vip

`[BuycraftX] Fetching all due players...
05:12:34 [INFORMATION] [BuycraftX] Fetched due players (1 found).

05:12:34 [INFORMATION] [BuycraftX] Executing commands for 1 online players...

05:12:35 [INFORMATION] [BuycraftX] Fetched 1 commands for player 'HexagonMC'.

05:12:35 [INFORMATION] [BuycraftX] Dispatching command 'bp user {uuid} group set vip' for player 'HexagonMC'.

05:12:35 [INFORMATION] CONSOLE executed command: /bp user {uuid} group set vip

05:12:35 [INFORMATION] The player {uuid} does not exist!
`
Clearly BungeePerms is saying that the user {uuid} is does not exist. So the plugin is not parsing the uuid correctly.
{name} does workj correctly

If using the command manually in the bungee console it is working:
`bp user 12af1a97-36df-4bb6-b6ba-03205d0a867e group set vip

05:19:00 [INFORMATION] CONSOLE executed command: /bp user 12af1a97-36df-4bb6-b6ba-03205d0a867e group set vip

05:19:00 [INFORMATION] Set group vip for player HexagonMC.
`

Tried both, isBungeeCord=true and =false in Buycraft config. Both didn't work
But this config setting was broken and misnamed in the old plugin aswell.

**Comment by minecrafter** [comment]
Please post the results of `/buycraft report`

**Comment by johnfriedrich** [comment]
http://pastebin.com/gprsRggA
Hm, shop is not in onlinemode.
Never saw this before and it worked before.(Old buycraft bukkit plugin with {uuid}
 Maybe I should change this and try again. This might be it. (Can't find the setting to change that...)

**Comment by minecrafter** [comment]
Your shop and server `online_mode` settings are mismatched. BuycraftX will not be able to use UUIDs in that scenario.

**Comment by johnfriedrich** [comment]
I forgot the online-mode setting in the webstore itself. That explains some issues with name changes in the past, where packets are not applied when the players changed their names after buying.
Anyway, contacted the support. I think they can change it.
Thanks for the important hint:)
