### ISSUE TITLE
Buycraft Signs

### ISSUE THREAD

**Issue by NytronMC** [BuycraftPlugin/BuycraftX#33]
I am trying to create Buycraft signs for recent donations, but I would like to filter it for a specific package.

I have found [buycraft_rp], but I don't know how to filter it.

**Comment by NytronMC** [comment]
Also, could you link me to a list or provide a list of all the signs and filters?

**Comment by minecrafter** [comment]
http://help.buycraft.net/article/14-purchase-signs and http://help.buycraft.net/article/13-how-to-set-up-recent-payments-signs-buysigns

**Comment by NytronMC** [comment]
I would like to **filter** the recent donation signs for a specific package.

> "I am trying to create Buycraft signs for recent donations, but I would like to filter it for a specific package."

**Comment by NytronMC** [comment]
# @minecrafter

**Comment by minecrafter** [comment]
Filtering is not currently possible. We may add it if there's strong demand for it.
