### ISSUE TITLE
Bungeecord error?

### ISSUE THREAD

**Issue by systemacc** [BuycraftPlugin/BuycraftX#34]
Not sure if im the only one experiencing the issue or if im doing something wrong. But on Bungeecord, the buy command shows all of the entire server(s) packages on every server. Such as, KitPvP server shows Creative and Skywars server packages and category. I have enabled Bungeecord and tried using the Bungeecord version of the plugin. If i am doing something wrong, there should be a wiki for this lol...

**Comment by LeeMcNeil** [comment]
This is an intended feature in the new plugin.

**Comment by systemacc** [comment]
Intended Feature?... Um.. LOL ok. Back to regular Buycraft. No idea why this is an intended feature, should at least be able to toggle it but k GG. Thanks

**Comment by minecrafter** [comment]
The BungeeCord plugin is meant for running commands on BungeeCord servers, not for integration with servers behind BungeeCord (but it can be used for that purpose).

Note that the old plugin will stop working 1 January 2017.

**Comment by systemacc** [comment]
can you please add back this feature, its so essential. Some players accidentally click the wrong server and purchase a package for the wrong server. Atleast an option to toggle it please? you probably wont do it since theres not a mass demand of it but alot of server owners arent updating to BuycraftX due to some issues like this one
