### ISSUE TITLE
Requesting Alias Commands for /Buy

### ISSUE THREAD

**Issue by ZachryWilsn** [BuycraftPlugin/BuycraftX#37]
I can not use Alias commands for /buy?
I use the "commands.yml" to make more options for /buy like /support and other common names.
Can you please add this ability back to buycraft or create a way to make more than one command for /buy.
I see this a a good thing for servers who want to have non-english commands and common /donate style commands.

Even if you have to Config the Alias in the Buycraft config I can see this helping owners a lot.

Thanks for your time.

**Comment by LeeMcNeil** [comment]
Sorry however we are not looking into implementing this. You can change the /buy command in the config file if you ever need to.

**Comment by ZachryWilsn** [comment]
I dont want to change /buy I was I want to translate it into other languages to allow people to use there own language to /buy. I was told you have someone trying to use your commands or something an thats your reason to negate the alias but for some this was not just a alias but a way for other players from around the world to have more easy of use. So if you would please at least talk about adding something similar back. It does not have to be the .commands file but some way for us owners to make the plugin easy to use for them via names/words that they know.

I kinda assumed since this would help more than me that you all might consider it.
Would this help if I get a petition of others who would want this as a option or is this just going to remain a oneway rd with Buycraft.

Sorry for sounding rude, Its not the intention. I just lost a feature Ive had for years with the buycraft with the update though.

Thanks again for your time a Effort with the plugin. Used you all for 4 years now.

**Comment by LeeMcNeil** [comment]
I've discussed this with our developer and we will be releasing this feature in the next version. Thanks for the in depth reasoning.

**Comment by ZachryWilsn** [comment]
Whoa, tbh I did not expect this response but Im true to the reason for the feature.
I also understand it was not a real part of buycraft but still allowed through the .command in spigot.

So again, Thank you so very much for your time and effort with this project.
