### ISSUE TITLE
config reset

### ISSUE THREAD

**Issue by SirSuso** [BuycraftPlugin/BuycraftX#4]
Hello, I dont know if the whole config reset or if its just the bungeecord option, but I change the bungeecord to true, restart the server and it go to false again.

**Comment by SirSuso** [comment]
This has happened few times now btw.

**Comment by minecrafter** [comment]
Unable to reproduce. The `is-bungeecord` option does nothing anyway.

**Comment by SirSuso** [comment]
Yes it does! If its not enabled then players wont receive their packages! I have even experimenting with it. When its disabled then the commands from buycraft just stays on due. So ye please fix it.

**Comment by SirSuso** [comment]
Also why do you close the thread when its not solved?

**Comment by minecrafter** [comment]
If I can't reproduce the issue, then I can't possibly fix it.

**Comment by minecrafter** [comment]
Can you please post the result of `/buycraft report`?

**Comment by SirSuso** [comment]
What you mean by reproduce the issue? Isnt it possible to fix the error that an option in the config kept getting reset after I changed? Yes I am going to post the buycraft report now.

**Comment by SirSuso** [comment]
http://pastebin.com/m9XwEZs0

**Comment by minecrafter** [comment]
I think this is an entirely different issue. Working on resolving this. Closing this report and opening another.
