### ISSUE TITLE
Fetching due players exception

### ISSUE THREAD

**Issue by zachschrier** [BuycraftPlugin/BuycraftX#40]
Getting this now about every 1 in 2 times Buycraft attempts to fetch the players queue. Just updated to BuycraftX. I imagine this is rather critical

http://hastebin.com/uciteremib.avrasm

**Comment by zachschrier** [comment]
This too: 

http://despawned.co/tFrjTGzDMQFc

**Comment by minecrafter** [comment]
First one is often due to your server's IPv6 stack being misconfigured - disabling it will work. This is a known issue.

The second issue is already known (#39).

**Comment by zachschrier** [comment]
Fixed the first exception, now getting this

http://despawned.co/SCoClByNEjQA

**Comment by zachschrier** [comment]
Do you know what this issue is or how to fix it? ^^

Really critical. No packages are going through at all

**Comment by minecrafter** [comment]
Seems to be an issue with your server's network connection to CloudFlare.
