### ISSUE TITLE
Not compatible with spigot 1.7.10

### ISSUE THREAD

**Issue by bob7l** [BuycraftPlugin/BuycraftX#44]
BuycraftX is not compatible with 1.7.10

http://pastebin.com/spNU17WV

I'm assuming this is on purpose considering you didn't list 1.7 within the compatible minecraft versions. The server was auto-updated to an incompatible build in that case - which is defiantly an issue within the older buycraft version i suppose.

**Comment by minecrafter** [comment]
You are correct, this is on purpose.

**Comment by minecrafter** [comment]
We released 6.8.3 a few days before 10.0. Some people went from 6.8.2 to 10.0.
