### ISSUE TITLE
Buycraft buy command

### ISSUE THREAD

**Issue by Johandrex** [BuycraftPlugin/BuycraftX#46]
Hello, I'm wondering if there's a way to use "/buy (CATEGORYID)". If there isn't such command please add it. Also I am wondering why it's possible to type "/buy" but not "/sudo (name) buy" or "/buycraftx:buy"

**Comment by minecrafter** [comment]
/buy is not handled by the Bukkit command system. This is a hack to 
bypass certain bad plugins.

**Comment by FlippantCactus** [comment]
Would be nice to be able to list categories with JSON implementation. 
i.e. it lists them, click on it and it inputs into your chat: /buy category:ranks, after pressing return will open up the category.

**Comment by johnfriedrich** [comment]
+1 That would be great. Otherwise we have to recreate chestmenus manually even if they are there but not accessible.

**Comment by gp-Airee** [comment]
+1 great idea.

**Comment by liam-wiltshire** [comment]
This issue is being closed as an old issue. For all support requests, please email support@buycraft.net. If you believe there is a plugin bug, please open a new issue.
