### ISSUE TITLE
Multiple language files

### ISSUE THREAD

**Issue by LeeMcNeil** [BuycraftPlugin/BuycraftX#47]
The plugin should ship with multiple language files (They're in the process of being translated into different languages now).

In the settings file the customer should be able to specify the language they want to use, and it should then read that language from a folder which includes the languages we release with. I've attached a screenshot for demonstration purposes.

<img width="433" alt="screen shot on 2016-04-15 at 13-50-16" src="https://cloud.githubusercontent.com/assets/2420485/14560595/1333ac3e-0311-11e6-8fac-60a868c2872d.png">

**Comment by minecrafter** [comment]
This is largely completed. We're just waiting on Crowdin translations.
