### ISSUE TITLE
BuycraftX GUI displaying irrelevant categories

### ISSUE THREAD

**Issue by Htgan** [BuycraftPlugin/BuycraftX#48]
The GUI currently displays all categories/packages regardless of which servers the categories/packages apply to. This is misleading and can show duplicate packages of the same name that are impossible for some players to understand/distinguish.

Please bring back the old buycraft GUI where only packages that apply to the current server will be displayed.

**Comment by LeeMcNeil** [comment]
@Htgan This is something we have realised needs to be fixed. Going to get this released soon.

**Comment by Htgan** [comment]
@LeeMcNeil Would you be so kind as to update me on the progress of this fix?

**Comment by shootcraft** [comment]
I had the same issue, have this bug been fix ?

**Comment by minecrafter** [comment]
This is an API issue, not a BuycraftX one.

@LeeMcNeil
