### ISSUE TITLE
Mixed-mode setups (online webstore, offline server) don't work

### ISSUE THREAD

**Issue by minecrafter** [BuycraftPlugin/BuycraftX#5]

**Comment by SirSuso** [comment]
Off topic, but when will the beta of your fixes be released? Really need it fast fixed on the server and I dont know how to put your source into an plugin myself.

**Comment by minecrafter** [comment]
Upon further investigation, mixed-mode setups (online mode webstore, offline mode server) don't work. I will add a warning for this.

**Comment by SirSuso** [comment]
What to do then, while running a bungee server? Since I have always used to have bungee to true in the buycraft config and then it have worked.

**Comment by minecrafter** [comment]
Make sure IP forwarding is enabled on your BungeeCord and Spigot installs.

**Bungee config.yml**: `ip_forward: true`
**Spigot config.yml**: `bungeecord: true`

**Comment by SirSuso** [comment]
ye they are

**Comment by SirSuso** [comment]
So did you fix it?

**Comment by minecrafter** [comment]
It should be fixed but I don't currently have a setup I can test with.

**Comment by SirSuso** [comment]
If you send it to me, I can test it for you?
