### ISSUE TITLE
Deploy to a maven repo

### ISSUE THREAD

**Issue by JamieSinn** [BuycraftPlugin/BuycraftX#50]
Maybe ask @md_5 to use the spigot one, or his repo?

**Comment by minecrafter** [comment]
I'll look into this, but I'll probably want to separate the plugin-related stuff from the client before I do so.

**Comment by JamieSinn** [comment]
okay, thanks!

**Comment by thekeenant** [comment]
[repo.minimum.io](https://repo.minimum.io)? :smiley:

**Comment by minecrafter** [comment]
I'm shutting that down, sorry.

**Comment by thomasb454** [comment]
How is this addition looking?

**Comment by toonsevrin** [comment]
I require a repository as well for my webhook.

**Comment by toonsevrin** [comment]
for the time being devs can use https://jitpack.io/#BuycraftPlugin/BuycraftX/v10.0

**Comment by thomasb454** [comment]
Awesome, thanks.



On Sat, Oct 15, 2016 at 12:33 PM +0100, "Toon Sevrin" <notifications@github.com<mailto:notifications@github.com>> wrote:


for the time being devs can use https://jitpack.io/#BuycraftPlugin/BuycraftX/v10.0

-

**Comment by toonsevrin** [comment]
PR #64 allows jitpack to compile more recent commits.

**Comment by liam-wiltshire** [comment]
This issue is being closed as an old issue. For all support requests, please email support@buycraft.net. If you believe there is a plugin bug, please open a new issue.
