### ISSUE TITLE
API Documentation?

### ISSUE THREAD

**Issue by JamieSinn** [BuycraftPlugin/BuycraftX#51]
Is there any documentation for plugins wanting to interface with BC? I'm not seeing much information or API at all. Any info on this would be great!

**Comment by minecrafter** [comment]
BuycraftX only provides an execution service and a barebones API client. BuycraftX is first and foremost a single-client plugin (which is itself). However, `buycraftx-common` provides the API client and the command processing system that all three BuycraftX ports share.

We might add documentation, but it won't be much. It'll be largely technical details.

**Comment by JamieSinn** [comment]
Technical details are always good with programmers :)

Is there going to be an extension of the api to include things like generating coupons, or enabling sales, etc?

**Comment by minecrafter** [comment]
That's outside of the scope of BuycraftX's API. The plugin API BuycraftX uses is meant primarily for executing server commands.

**Comment by JamieSinn** [comment]
Ah, I see. Thanks.

**Comment by JamieSinn** [comment]
Would it be possible to make either a custom API, or an extension onto BuycraftX that would be able to give a package to a user programmically? The idea is that I would be able to send a request to BC, and have in the request the user's uuid to apply it to. Probably out of the scope, not sure if possible either, as there's probably no infrastructure available.

**Comment by minecrafter** [comment]
Once again, that's out of scope for BuycraftX.

**Comment by LeeMcNeil** [comment]
@JamieSinn Hey, this isn't something which is going to be included in the Plugin API. It is however being released in our general API which should be available for the public to use in the upcoming weeks. Keep an eye out on our blog/twitter etc. Thank you.

**Comment by JamieSinn** [comment]
That's awesome, thanks!
