### ISSUE TITLE
Cant seem to build ever since this commit:

### ISSUE THREAD

**Issue by andrewkm** [BuycraftPlugin/BuycraftX#52]
https://github.com/BuycraftPlugin/BuycraftX/commit/ff95522ec0da27d50384baeef6602fd01eb918a2
http://ci.md-5.net/job/BuycraftX/23/console

Some reason this build and above aren't building.

**Comment by minecrafter** [comment]
ff95522 refactored shared plugin components (things non-API related) into a new module (`plugin-shared`). Add this module and things should work normally.

**Comment by minecrafter** [comment]
@andrewkm You should also compile `common` as well. There may be changes there that may cause unexpected behavior if it's not recompiled as well.

**Comment by andrewkm** [comment]
@minecrafter Alright thank you :)
I'm running with this now and it seems to work fine:
clean install package -pl bukkit,common,plugin-shared,bungeecord

Assuming that's correct?

**Comment by minecrafter** [comment]
That's correct
