### ISSUE TITLE
Information on using API

### ISSUE THREAD

**Issue by sebastianbinder** [BuycraftPlugin/BuycraftX#53]
Hey there. I'm wondering if it was possible to use BuycraftX not only for receiving information about payments that have been done.
My custom Bungeecord server plugin listens to Votifier votes. After a certain amount of votes by one player I'd like to give this player one of my packages on Buycraft for free.
Is there any way of using BuycraftX the other way round? Example creating a `new Purchase(ProxiedPlayer, PackageId)`, which then gets send to Buycraft and shows up as a manual transaction.
Of course, then the normal BuycraftX plugin should get the "payment notification" and send the commands of that package to the server - as usual.
So is there any payment API in java I can use in my custom plugin?
Thank you for your information :)

**Comment by minecrafter** [comment]
This feature is out of scope for BuycraftX. This sounds like a feature that should be in a general Buycraft API, which we're working on. Keep an eye out on Twitter and our blog for more information when it comes.
