### ISSUE TITLE
Build 34 error.

### ISSUE THREAD

**Issue by andrewkm** [BuycraftPlugin/BuycraftX#55]
http://pastie.org/pastes/10846019/text?key=vtu1sbtnc3qahdj0bm8wa

**Comment by andrewkm** [comment]
Now getting spammed with http://pastie.org/pastes/10846021/text?key=lvf0qi8mtgkloj2zzzeww

**Comment by andrewkm** [comment]
Nvm: looks like buycraft is down.

**Comment by minecrafter** [comment]
Not much we can do about transient service failures. This usually clears itself up, however.
