### ISSUE TITLE
Build Fails - Internal Error on Repo

### ISSUE THREAD

**Issue by JamieSinn** [BuycraftPlugin/BuycraftX#56]
http://ci.ecocitycraft.com/job/BuycraftX/46/console

**Comment by minecrafter** [comment]
It looks like your CI setup doesn't seem to like the SNI on @InventivetalentDev's repository. Somehow, [our Jenkins setup works](http://ci.buycraft.net/job/BuycraftX/) (it's Ubuntu 14.04 and Java 8), and so does my Mac.

I changed the URL to HTTP so it should work now.

**Comment by JamieSinn** [comment]
Great! Thanks!
