### ISSUE TITLE
Please fill in all form fields error

### ISSUE THREAD

**Issue by Sikatsu** [BuycraftPlugin/BuycraftX#57]
Hey,

On my website I keep receiving the error ''Please fill in all form fields'' even while everything is filled in correctly. How can I fix this? (Or how to disable the requirement of form fields?)

I'm quite new with BuyCraft, heres the webstore: shop.villagercraft.eu

Thanks in advance.

**Comment by LeeMcNeil** [comment]
Hi,

You're best emailing our customer support via support@buycraft.net - this Github page is only for issues related to the plugin and not the website.

Regards
