### ISSUE TITLE
/buy command interferes with other commands.

### ISSUE THREAD

**Issue by andrewkm** [BuycraftPlugin/BuycraftX#58]
We have a command known as /buyfeature
The buycraft /buy command intereferes with that.

/buy123
/buyfeature
etc.... all goes directly to /buy

This should not be the case.

**Comment by minecrafter** [comment]
Was already fixed in 8ecdfff but we need to do a re-release

@LeeMcNeil

**Comment by andrewkm** [comment]
I'm on build 47
http://ci.ecocitycraft.com/job/BuycraftX/

So fixed in 48?

**Comment by minecrafter** [comment]
Yes
