### ISSUE TITLE
Include package in RecentPayment and make limit higher

### ISSUE THREAD

**Issue by RobiRami** [BuycraftPlugin/BuycraftX#60]
Hi,

I would like to get the name of the package(s) of a RecentPayment. Please add this. I know it's possible by manually GETting /payments but it's easier via the API.

Could the amount of recent payments for getRecentPayments be raised from 100 to something higher ?

**Comment by minecrafter** [comment]
BuycraftX is not the place for discussing suggestions for the plugin API. Please email support@buycraft.net for API suggestions.
