### ISSUE TITLE
Recent purchase signs - Mac issue

### ISSUE THREAD

**Issue by hfmachin** [BuycraftPlugin/BuycraftX#61]
Getting this issue on MC 1.10.2 and BC 10.1.3 for Mac only. 

![2016-09-02_10 37 27](https://cloud.githubusercontent.com/assets/3988100/18199871/2ddc5bba-70fa-11e6-9bc9-cb2cb8f9f761.png)

**Comment by minecrafter** [comment]
I'll see if I can resolve this. It's probably a simple issue...

**Comment by minecrafter** [comment]
Might be fixed now.
