### ISSUE TITLE
Increase code reuse

### ISSUE THREAD

**Issue by minecrafter** [BuycraftPlugin/BuycraftX#62]
At the moment, while a small core of the plugin is reused and shared across all our ports, there is still a lot of potential for code reuse.

**Comment by minecrafter** [comment]
This will be a goal with the 10.2 release. Some work was done for this for 10.1.4 as well.

So far, `java.util.logging` handlers for Bugsnag have been unified with 579bbf2f.

**Comment by VCraftMCPE** [comment]
Hey can u make a BuyCraft plugin for PocketMine??

**Comment by minecrafter** [comment]
@VCraftMCPE This is the wrong place to ask.

**Comment by liam-wiltshire** [comment]
There is a version of the plugin now available for PocketMine. If you sign up at https://www.buycraft.net, you will be able to download the PocketMine plugin once registered.
