### ISSUE TITLE
Multiple plugins using same key causes duplicate calls

### ISSUE THREAD

**Issue by toonsevrin** [BuycraftPlugin/BuycraftX#65]
Though this is easily solvable by the client: When there are multiple StandaloneBuycraftRunners (/plugins) using the same key, the commands may be send to more than just 1 runner.

**How could this cause issues:**
- if the update increments a value (for example # of donation chests), this may be incremented multiple times with a single payment

**How can we solve this without buycraft's intervention:**
With every transaction, generate a unique transaction id that is stored in an atomic database when the transaction is first processed, if the other runners see the id is already stored, they don't handle the event.
Maybe this is the best way to do it as you know the payment is made. But still it would be nice to have the option :)

This is by no means a plugin issue but maybe this should be configurable on the BuyCraft end.

**Comment by minecrafter** [comment]
First, **this is the wrong avenue**. You need to contact support@buycraft.net.

However, this is also **by design**. One Buycraft server means one client is processing commands. There are very few compelling cases where it is worth running multiple clients for one server. If you seriously need this functionality, you can always use a separate server key.

**Comment by toonsevrin** [comment]
Sorry for posting the issue here, wasn't sure if this was actually managed by the bc team. I'm not sure how Hypixel integrates buycraft but in the case when you have many bungeecord servers it becomes attractive to not use a buycraft plugin and let it be handled by a service (to make this service highly available, you run multiple instances of it simultaneously).
Anyways, was a stupid issue of me, as I already wrote the solution (atomic database)...
