### ISSUE TITLE
Old API being shutdown.

### ISSUE THREAD

**Issue by ghost** [BuycraftPlugin/BuycraftX#67]
I noticed that in my server console I receive a message about buycraft shutting down the API the older plugin relies on. I still use the older plugin on my 1.7.10 and 1.5.2 servers, are there builds of BuycraftX that support these versions?

**Comment by minecrafter** [comment]
The latest versions of BuycraftX support 1.7.10.

Unfortunately for 1.5.2, you're out of luck. You can try backporting BuycraftX to 1.5.2 yourself but we will not provide any assistance.
