### ISSUE TITLE
Error with Buycraft on my server; Donations getting processed but commands not getting executed

### ISSUE THREAD

**Issue by IamMully** [BuycraftPlugin/BuycraftX#68]
Please help.

The error (cutoff a little bit because I accidentally deleted the rest on the log. sorry..) :

buycraft error at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[buycraft.jar:?] at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:60) ~[buycraft.jar:?] at net.buycraft.plugin.client.ProductionApiClient.get(ProductionApiClient.java:64) ~[buycraft.jar:?] at net.buycraft.plugin.client.ProductionApiClient.retrieveDueQueue(ProductionApiClient.java:94) ~[buycraft.jar:?] at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:63) [buycraft.jar:?] at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:37) [buycraft.jar:?] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-db6de12-18fbb24] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) [spigot.jar:git-Spigot-db6de12-18fbb24] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66] Caused by: java.net.SocketException: Socket closed at java.net.SocketInputStream.read(SocketInputStream.java:203) ~[?:1.8.0_66] at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_66] at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_66] at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_66] at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973

**Comment by liam-wiltshire** [comment]
This issue is being closed as an old issue. For all support requests, please email support@buycraft.net. If you believe there is a plugin bug, please open a new issue.
