### ISSUE TITLE
/buy command Error NoSuchMethodError

### ISSUE THREAD

**Issue by JoeSGT** [BuycraftPlugin/BuycraftX#82]
like the title said but here are my version's
Sponge spongeforge-1.12.2-2555-7.0.0-BETA-2774.jar
https://pastebin.com/KYJePmq4

**Comment by ghost** [comment]
Hi,

It looks like this is an issue related to SpongeForge:
https://github.com/SpongePowered/SpongeForge/issues/1727

**Comment by ghost** [comment]
Hi, thanks for warning us about this. We are currently working fixing this, please keep an eye out for future plugin releases.

**Comment by liam-wiltshire** [comment]
Due to changes in the Sponge API, we will be releasing a new plugin that is built using a newer API version - however this will *not* be compatible with older versions of Sponge.

This release will happen in the next few days - keep an eye on your Buycraft control panel!
