### ISSUE TITLE
Unable to use material names in "GUI Item"

### ISSUE THREAD

**Issue by johnfriedrich** [BuycraftPlugin/BuycraftX#83]
It's not possible to use material names in GUI via Buycraft Website.
Even the handling of GUI icons is still numerical. They are deprecated since four years and will break with 1.13 shortly.
So the possibility to use material names would be great!

**Comment by ghost** [comment]
Hi,

Thanks for the suggestion, this is something that we're going to be working on. Just keep an eye out for upcoming updates of the plugin.

**Comment by ghost** [comment]
Hi, we have updated our plugin so that it now accepts material names, thanks again.

**Comment by johnfriedrich** [comment]
Thanks a lot!
