### ISSUE TITLE
Introduce /buy player args[] to easily open defined categories for players

### ISSUE THREAD

**Issue by johnfriedrich** [BuycraftPlugin/BuycraftX#84]
This would allow admins to create signs or clickable links in chat to open buy guis for players. 

Let's say you have a sign that advertises cool playersheads. When you click the sign that links 
/buy player_cling_thesign server1 booster heads
the menu heads shows up and the player can directly choose a head to buy.

This would elimate clicking though dozens of menus and submenus

**Comment by ghost** [comment]
Hi,

We appreciate your suggestion, we'll add this to our list of possible development so look out for upcoming versions of the plugin!

**Comment by ghost** [comment]
Hi, we have updated our plugin and added a `/buycraft sendlink` which will allow you to send buy links to your players in-game.

**Comment by johnfriedrich** [comment]
Hey, great! Looking forward to implement that in our guis. Thanks a lot
