### ISSUE TITLE
Add "Note" to coupon API

### ISSUE THREAD

**Issue by MedicOP** [BuycraftPlugin/BuycraftX#88]
https://documentation.buycraft.net/documentation/#create-a-coupon

There is no parameter for the note

**Comment by ghost** [comment]
Hi, thanks for the suggestion, I will add that to our list of development and let you know once the note parameter has been added.

**Comment by liam-wiltshire** [comment]
This is now supported:
https://documentation.buycraft.net/documentation/#create-a-coupon
