### ISSUE TITLE
Make configurable how many commands are executed per tick

### ISSUE THREAD

**Issue by MedicOP** [BuycraftPlugin/BuycraftX#90]
Can it be made configurable how many commands are executed per tick? Ever since updating from Buycraft 6.8 to BuycraftX couple of days ago, I'm noticing some issues with PEX when adding multiple permissions for the same user. 

Unfortunately PEX is dumb and re-writes all permissions every time a single add is done. When 2 permissions are added at the exact same time it sometimes causes only 1 permission to be added. This was not a problem in Buycraft 6.8 because execution time of commands was capped at 0.5 milliseconds per tick.

**Comment by minecrafter** [comment]
You may be interested to know that PermissionsEx is no longer supported and that the author recommends [LuckPerms](https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) instead.

**Comment by MedicOP** [comment]
I'm aware, but I have other plugins that depend on PEX that I'm too lazy to edit. I've just finished implementing a private fix for this PEX bug, but it would still be nice to have the ability to keep the same behavior as Buycraft 6.8

**Comment by MedicOP** [comment]
Any plans on this being added?

**Comment by liam-wiltshire** [comment]
There isn't any plan to implement a feature such as this at the moment - you are more then welcome to fork the plugin or to submit a patch to add support for this which we will of course consider, but at this moment in time there is no plan in our roadmap to add a change such as this.

**Comment by MedicOP** [comment]
It really isn't a significant change, not sure why you are against adding it.

PR:
https://github.com/BuycraftPlugin/BuycraftX/pull/115
