### ISSUE TITLE
Improper DNSSEC setup?

### ISSUE THREAD

**Issue by MedicOP** [BuycraftPlugin/BuycraftX#93]
/var/log/messages is spammed with these errors

```
validating @0x7f38bc0020f0: api.buycraft.net A: no valid signature found
```

**Comment by MedicOP** [comment]
still happening

**Comment by MedicOP** [comment]
still happening

**Comment by liam-wiltshire** [comment]
This would appear to be a problem with a configuration your side - DNSSEC appears to be correctly configured our side (see https://dnssec-debugger.verisignlabs.com/api.buycraft.net), and this isn't something that we've changed recently.
