### ISSUE TITLE
Matching for "like player name" instead of exact for "isPlayerOnline"

### ISSUE THREAD

**Issue by bob7l** [BuycraftPlugin/BuycraftX#99]
https://github.com/BuycraftPlugin/BuycraftX/blob/master/bukkit/src/main/java/net/buycraft/plugin/bukkit/BukkitBuycraftPlatform.java#L66

getPlayer(String name) function returns a player with a name LIKE "name". You need to put getPlayerExact. This is causing tons of problems on my server for players with like names.

**Comment by ghost** [comment]
Thank you for making us aware of this, I will add this to our high priority list to ensure that the issue gets looked into at our earliest convenience. Once progress is made I shall inform you here.

**Comment by ghost** [comment]
[This](https://github.com/BuycraftPlugin/BuycraftX/commit/e14228ea3b80c39c4c8f890859be536d2e2a4b0b) change can be found in the latest version of our plugin. You can download the latest version of our plugin by going to https://server.buycraft.net/plugins.
